#!/usr/bin/env node
/**
 * Manage Codex-only project-local shortcuts for Impeccable root commands.
 *
 * Usage:
 *   node skills/impeccable/scripts/pin.mjs pin craft
 *   node skills/impeccable/scripts/pin.mjs unpin craft
 */

import {
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  rmSync,
  writeFileSync,
} from 'node:fs';
import { join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const MANAGED_MARKER_PREFIX = '<!-- impeccable-pin';
const SKILLS_DIR_NAME = 'skills';

export const PINNABLE_COMMANDS = {
  craft: {
    description: 'Shortcut for $impeccable craft.',
    argumentHint: '[feature description]',
    mode: 'Craft Mode',
  },
  teach: {
    description: 'Shortcut for $impeccable teach.',
    argumentHint: '',
    mode: 'Teach Mode',
  },
  document: {
    description: 'Shortcut for $impeccable document.',
    argumentHint: '[documentation target]',
    mode: 'Document Mode',
  },
  extract: {
    description: 'Shortcut for $impeccable extract.',
    argumentHint: '[target]',
    mode: 'Extract Mode',
  },
};

function managedMarker(command) {
  return `${MANAGED_MARKER_PREFIX} command="${command}" -->`;
}

function listCommands() {
  return Object.keys(PINNABLE_COMMANDS).join(', ');
}

function validateCommand(command) {
  if (!PINNABLE_COMMANDS[command]) {
    throw new Error(
      `Unknown pin target "${command}". Valid targets: ${listCommands()}. ` +
        'Standalone commands such as audit, polish, and layout already ship as Codex skills.',
    );
  }
}

function frontmatter(command) {
  const meta = PINNABLE_COMMANDS[command];
  const lines = [
    '---',
    `name: ${command}`,
    `description: "${meta.description}"`,
  ];
  if (meta.argumentHint) {
    lines.push(`argument-hint: "${meta.argumentHint}"`);
  }
  lines.push('---');
  return lines.join('\n');
}

function shortcutBody(command) {
  const meta = PINNABLE_COMMANDS[command];
  return `${managedMarker(command)}

This is a managed shortcut generated by \`$impeccable pin ${command}\`.

Treat this invocation exactly as \`$impeccable ${command}\` with the user's same arguments. Load the installed \`impeccable\` skill from the active Codex skill list, follow its ${meta.mode}, and preserve the user's original task.

Do not edit this file by hand. Remove it with \`$impeccable unpin ${command}\`.`;
}

export function renderShortcut(command) {
  validateCommand(command);
  return `${frontmatter(command)}\n\n${shortcutBody(command)}\n`;
}

export function projectPaths(projectRoot, command) {
  const root = resolve(projectRoot);
  const skillDir = join(root, SKILLS_DIR_NAME, command);
  return {
    root,
    skillDir,
    skillFile: join(skillDir, 'SKILL.md'),
  };
}

export function readExistingShortcut(skillFile) {
  if (!existsSync(skillFile)) return null;
  return readFileSync(skillFile, 'utf-8');
}

export function isManagedShortcut(content, command) {
  return typeof content === 'string' && content.includes(managedMarker(command));
}

export function pinCommand({ projectRoot = process.cwd(), command }) {
  validateCommand(command);
  const { skillDir, skillFile } = projectPaths(projectRoot, command);
  const existing = readExistingShortcut(skillFile);

  if (existing && isManagedShortcut(existing, command)) {
    return {
      changed: false,
      message: `Already pinned: $${command} is managed by Impeccable.`,
      skillFile,
    };
  }

  if (existing) {
    throw new Error(`Refusing to overwrite existing skill: ${skillFile}`);
  }

  if (existsSync(skillDir) && readdirSync(skillDir).length > 0) {
    throw new Error(`Refusing to write into non-empty skill directory: ${skillDir}`);
  }

  mkdirSync(skillDir, { recursive: true });
  writeFileSync(skillFile, renderShortcut(command), 'utf-8');
  return {
    changed: true,
    message: `Pinned $${command} as a shortcut for $impeccable ${command}.`,
    skillFile,
  };
}

export function unpinCommand({ projectRoot = process.cwd(), command }) {
  validateCommand(command);
  const { skillDir, skillFile } = projectPaths(projectRoot, command);
  const existing = readExistingShortcut(skillFile);

  if (!existing) {
    return {
      changed: false,
      message: `No managed shortcut found for $${command}.`,
      skillFile,
    };
  }

  if (!isManagedShortcut(existing, command)) {
    throw new Error(`Refusing to remove unmanaged skill: ${skillFile}`);
  }

  rmSync(skillFile, { force: true });
  if (existsSync(skillDir) && readdirSync(skillDir).length === 0) {
    rmSync(skillDir, { recursive: true, force: true });
  }

  return {
    changed: true,
    message: `Unpinned $${command}.`,
    skillFile,
  };
}

export function runPinCli(argv = process.argv.slice(2), projectRoot = process.cwd()) {
  const [action, command] = argv;
  if (!action || !command || !['pin', 'unpin'].includes(action)) {
    throw new Error(`Usage: node pin.mjs <pin|unpin> <${listCommands().replaceAll(', ', '|')}>`);
  }

  return action === 'pin'
    ? pinCommand({ projectRoot, command })
    : unpinCommand({ projectRoot, command });
}

const currentFile = resolve(fileURLToPath(import.meta.url));
const invokedFile = process.argv[1] ? resolve(process.argv[1]) : null;

if (invokedFile === currentFile) {
  try {
    const result = runPinCli();
    console.log(result.message);
    console.log(result.skillFile);
  } catch (error) {
    console.error(error.message);
    process.exitCode = 1;
  }
}
