#!/usr/bin/env node

/**
 * Build system for the Codex-only skill distribution.
 *
 * Produces:
 * - `dist/codex/skills/`
 * - `dist/codex.zip` for direct download/installation
 *
 * The website and download API read from those generated outputs.
 */

import path from 'path';
import fs from 'fs';
import { fileURLToPath } from 'url';
import {
  readSourceFiles,
  readPatterns,
  readSkillPatterns,
  stashPerProjectArtifacts,
  restorePerProjectArtifacts,
} from './lib/utils.js';
import { createTransformer, PROVIDERS } from './lib/transformers/index.js';
import { createAllZips } from './lib/zip.js';

/**
 * Generate authoritative counts from source data and write to site/public/js/generated/counts.js.
 * Also validates that key HTML files reference the correct numbers.
 */
function generateCounts(rootDir, skills) {
  // Count active (non-deprecated) user-invocable commands
  const activeCommands = skills.filter(s => {
    if (!s.userInvocable) return false;
    const content = fs.readFileSync(s.filePath, 'utf-8');
    return !content.includes('DEPRECATED');
  });
  const commandCount = activeCommands.length;

  // Count detection rules from impeccable package
  const detectPkgPath = path.join(rootDir, 'cli/engine/detect-antipatterns.mjs');
  const detectorSrc = fs.readFileSync(detectPkgPath, 'utf-8');
  const ruleIds = new Set();
  for (const match of detectorSrc.matchAll(/^\s+id: '([^']+)'/gm)) {
    ruleIds.add(match[1]);
  }
  const detectionCount = ruleIds.size;

  // Write generated counts module
  const genDir = path.join(rootDir, 'site/public/js/generated');
  fs.mkdirSync(genDir, { recursive: true });
  fs.writeFileSync(path.join(genDir, 'counts.js'),
    `// GENERATED by build.js — do not edit\n` +
    `export const COMMAND_COUNT = ${commandCount};\n` +
    `export const DETECTION_COUNT = ${detectionCount};\n`
  );

  // Validate counts in key files
  const filesToCheck = [
    'site/pages/index.astro',
    'site/pages/cheatsheet.astro',
    'README.md',
    'NOTICE.md',
    'AGENTS.md',
    'plugins/impeccable/.codex-plugin/plugin.json',
  ];

  let errors = 0;
  for (const relPath of filesToCheck) {
    const absPath = path.join(rootDir, relPath);
    if (!fs.existsSync(absPath)) continue;
    const content = fs.readFileSync(absPath, 'utf-8');

    // Check for stale command counts (look for "N commands" or "N skills" patterns)
    // Strip changelog list content to avoid flagging historical counts
    const strippedContent = content.replace(/<ul class="changelog-items">[\s\S]*?<\/ul>/g, '');
    const countPattern = /\b(\d+)\s+(design\s+)?(commands|skills|steering commands)/gi;
    for (const match of strippedContent.matchAll(countPattern)) {
      const num = parseInt(match[1]);
      // Allow 1 (for "1 skill") and the correct count
      if (num !== commandCount && num !== 1) {
        console.error(`  ❌ ${relPath}: found "${match[0]}" but active command count is ${commandCount}`);
        errors++;
      }
    }

    // Check for stale detection counts
    const detectPattern = /\b(\d+)\s+(deterministic\s+)?(checks|patterns|rules|detections)/gi;
    for (const match of content.matchAll(detectPattern)) {
      const num = parseInt(match[1]);
      if (num !== detectionCount && num > 10) { // ignore small numbers like "3 patterns"
        console.error(`  ❌ ${relPath}: found "${match[0]}" but detection count is ${detectionCount}`);
        errors++;
      }
    }
  }

  if (errors > 0) {
    console.error(`\n❌ ${errors} stale count reference(s) found. Update them to match source of truth.`);
  }

  console.log(`✓ Generated counts: ${commandCount} commands, ${detectionCount} detection rules`);
  return errors;
}

/**
 * Cross-validate that every detection rule with a `skillGuideline` has a
 * matching DON'T line in the right section of skills/impeccable/SKILL.md.
 *
 * This is the linchpin of the single-source-of-truth design: it catches drift
 * between the engine's ANTIPATTERNS and the human-written DO/DON'T prose.
 *
 * Returns the number of validation errors. Build fails if > 0.
 */
function validateAntipatternRules(rootDir) {
  const detectPath = path.join(rootDir, 'cli/engine/detect-antipatterns.mjs');
  const src = fs.readFileSync(detectPath, 'utf-8');
  const apMatch = src.match(/const ANTIPATTERNS = \[([\s\S]*?)\n\];/);
  if (!apMatch) {
    console.error('  ❌ Could not extract ANTIPATTERNS from detect-antipatterns.mjs');
    return 1;
  }
  const antipatterns = new Function(`return [${apMatch[1]}]`)();
  const { antipatterns: skillSections } = readSkillPatterns(rootDir);

  // Build section -> joined-DON'T-text lookup for substring matching.
  // Lowercased for case-insensitive matching: my XML refactor uses sentence-
  // case "DO NOT nest cards" while the rules' skillGuideline strings are
  // sentence-cased "Nest cards inside cards" (a fragment from the original
  // markdown bullet "**DON'T**: Nest cards inside cards.").
  const sectionText = {};
  for (const section of skillSections) {
    sectionText[section.name] = section.items.join('\n').toLowerCase();
  }

  let errors = 0;
  let validated = 0;
  for (const rule of antipatterns) {
    if (!rule.skillGuideline) continue;
    if (!rule.skillSection) {
      console.error(`  ❌ Rule '${rule.id}' declares skillGuideline but no skillSection`);
      errors++;
      continue;
    }
    const text = sectionText[rule.skillSection];
    if (!text) {
      console.error(`  ❌ Rule '${rule.id}': skillSection '${rule.skillSection}' has no DON'T lines in skills/impeccable/SKILL.md`);
      errors++;
      continue;
    }
    if (!text.includes(rule.skillGuideline.toLowerCase())) {
      console.error(`  ❌ Rule '${rule.id}': skillGuideline '${rule.skillGuideline}' not found in any DON'T of section '${rule.skillSection}' in skills/impeccable/SKILL.md`);
      errors++;
      continue;
    }
    validated++;
  }

  if (errors > 0) {
    console.error(`\n❌ ${errors} anti-pattern rule(s) drift between cli/engine/detect-antipatterns.mjs and skills/impeccable/SKILL.md`);
  } else {
    console.log(`✓ Validated ${validated}/${antipatterns.length} anti-pattern rules against impeccable SKILL.md`);
  }
  return errors;
}

/**
 * Scan user-facing copy for prose tells that make the public site feel generic.
 * Only scans files where we author copy, not vendored or generated output.
 *
 * Returns the number of occurrences found.
 */
function validateProse(rootDir) {
  const targets = [
    'site/content',
    'site/components',
    'site/layouts',
    'site/pages',
    'README.md',
    'README.npm.md',
    'scripts/lib/sub-pages-data.js',
  ];
  const extensions = new Set(['.astro', '.html', '.md', '.js', '.mjs', '.css', '.ts']);
  const emDashPatterns = [/—/g, /&mdash;/gi, /&#8212;/gi, /&#x2014;/gi];
  const phraseRules = [
    { re: /\bload-bearing\b/i, rationale: 'AI tell. Stolen-engineer diction; name what the thing actually does.' },
    { re: /\bhighest-leverage\b/i, rationale: 'AI tell. Vague claim of impact; say what specifically pays off.' },
    { re: /\bbiggest unlock\b/i, rationale: 'Marketing-speak; describe the actual change.' },
    { re: /\breflex defaults?\b/i, rationale: 'Internal jargon leaking into user copy; say "first guesses" or name the behavior.' },
    { re: /\bcollapses? into monoculture\b/i, rationale: 'Internal eval-speak; describe what actually went wrong.' },
    { re: /\bdata-driven\b/i, rationale: 'Empty marketing adjective; cite the evidence instead.' },
    { re: /\bseamless(?:ly)?\b/i, rationale: 'Hollow positive; say what specifically works without friction.' },
    { re: /\brobust(?:ness)?\b/i, rationale: 'Hollow positive; cite the failure mode it handles.' },
    { re: /\bdelves?\b|\bdelved\b|\bdelving\b/i, rationale: 'Top AI tell; use "explore", "look at", or delete the setup.' },
    { re: /\belevate(?:s|d)?\b/i, rationale: 'Marketing verb; use the specific verb.' },
    { re: /\bempower(?:s|ed|ing)?\b/i, rationale: 'Marketing verb; use "let you" or "make possible".' },
    { re: /\bunderscore(?:s|d)?\b/i, rationale: 'AI tell; use "show" or "make clear".' },
    { re: /\bpivotal\b/i, rationale: 'Hollow positive; use "central", "key", or describe the role.' },
    { re: /\bin today's\b/i, rationale: 'Throat-clearing opener; start at the point.' },
    { re: /\bgone are the days\b/i, rationale: 'Throat-clearing; make the point directly.' },
    { re: /\bwhether you're\b/i, rationale: 'Audience-pandering; pick one reader.' },
    { re: /\blet's dive in\b/i, rationale: 'Throat-clearing; just start.' },
    { re: /\bin summary\b|\bin conclusion\b/i, rationale: 'Summarizing closer; end on the strongest sentence.' },
    { re: /\bmoreover\b|\bfurthermore\b/i, rationale: 'Transition crutch; drop it, use "also", or restructure.' },
    { re: /\btapestry\b/i, rationale: 'AI scenery noun; cut it.' },
  ];
  let errors = 0;

  const checkLine = (line, rel, lineNum) => {
    for (const re of emDashPatterns) {
      if (re.test(line)) {
        console.error(`  ❌ ${rel}:${lineNum}: em dash in copy → ${line.trim().slice(0, 120)}`);
        console.error('        Use commas, colons, semicolons, periods, or parentheses.');
        errors++;
        re.lastIndex = 0;
        break;
      }
      re.lastIndex = 0;
    }
    if (/ -- /.test(line)) {
      console.error(`  ❌ ${rel}:${lineNum}: \` -- \` em-dash substitute → ${line.trim().slice(0, 120)}`);
      console.error('        Pick real punctuation.');
      errors++;
    }
    for (const rule of phraseRules) {
      if (rule.re.test(line)) {
        const matched = line.match(rule.re)?.[0] ?? '';
        console.error(`  ❌ ${rel}:${lineNum}: "${matched}" → ${line.trim().slice(0, 120)}`);
        console.error(`        ${rule.rationale}`);
        errors++;
      }
    }
  };

  const scan = (absPath, rel) => {
    const stat = fs.statSync(absPath);
    if (stat.isDirectory()) {
      for (const entry of fs.readdirSync(absPath)) {
        scan(path.join(absPath, entry), path.join(rel, entry));
      }
      return;
    }
    if (!extensions.has(path.extname(absPath))) return;
    const src = fs.readFileSync(absPath, 'utf-8');
    const lines = src.split('\n');
    lines.forEach((line, i) => checkLine(line, rel, i + 1));
  };

  for (const target of targets) {
    const full = path.join(rootDir, target);
    if (fs.existsSync(full)) scan(full, target);
  }

  if (errors === 0) {
    console.log(`✓ Prose validator: no AI tells in user-facing copy`);
  } else {
    console.error(`\n❌ ${errors} prose issue(s) in user-facing copy. See STYLE.md for the rules.`);
  }
  return errors;
}

/**
 * Narrow prose check for the impeccable skill source.
 *
 * LLM-facing reference instructions legitimately use repetition and checklists,
 * so the public-copy validator would be too broad here. This guard enforces
 * only the mechanical wins: em dashes, double-hyphen substitutes, and the small
 * denylist phrases with no useful technical reading.
 *
 * Returns the number of occurrences found.
 */
function validateSkillProse(rootDir) {
  const target = 'skills/impeccable';
  const extensions = new Set(['.md']);
  const emDashPatterns = [/—/g, /&mdash;/gi, /&#8212;/gi, /&#x2014;/gi];
  const phraseRules = [
    { re: /\bload-bearing\b/i, rationale: 'AI tell. Name what the thing actually does.' },
    { re: /\bhighest-leverage\b/i, rationale: 'AI tell. Say what specifically pays off.' },
    { re: /\bbiggest unlock\b/i, rationale: 'Marketing-speak. Describe the actual change.' },
    { re: /\breflex defaults?\b/i, rationale: 'Internal jargon. Say "instincts" or "first guesses".' },
    { re: /\bcollapses? into monoculture\b/i, rationale: 'Eval-speak. Describe what actually went wrong.' },
    { re: /\bdata-driven\b/i, rationale: 'Empty marketing adjective. Cite the data instead.' },
    { re: /\bdelves?\b|\bdelved\b|\bdelving\b/i, rationale: 'Top AI tell. Use "explore" or "look at".' },
    { re: /\btapestry\b/i, rationale: 'AI scenery noun. Cut.' },
    { re: /\bin today's\b/i, rationale: 'Throat-clearing opener. Start at the point.' },
    { re: /\bgone are the days\b/i, rationale: 'Throat-clearing. Make the point directly.' },
    { re: /\blet's dive in\b/i, rationale: 'Throat-clearing. Just start.' },
    { re: /\bin summary\b|\bin conclusion\b/i, rationale: 'Summarizing closer. End on the strongest sentence.' },
  ];
  let errors = 0;

  const checkLine = (line, rel, lineNum) => {
    for (const re of emDashPatterns) {
      if (re.test(line)) {
        console.error(`  ❌ ${rel}:${lineNum}: em dash in skill source → ${line.trim().slice(0, 120)}`);
        console.error('        Use commas, colons, semicolons, periods, or parentheses.');
        errors++;
        re.lastIndex = 0;
        break;
      }
      re.lastIndex = 0;
    }
    if (/ -- /.test(line)) {
      console.error(`  ❌ ${rel}:${lineNum}: \` -- \` em-dash substitute → ${line.trim().slice(0, 120)}`);
      console.error('        Pick real punctuation.');
      errors++;
    }
    for (const rule of phraseRules) {
      if (rule.re.test(line)) {
        const matched = line.match(rule.re)?.[0] ?? '';
        console.error(`  ❌ ${rel}:${lineNum}: "${matched}" → ${line.trim().slice(0, 120)}`);
        console.error(`        ${rule.rationale}`);
        errors++;
      }
    }
  };

  const scan = (absPath, rel) => {
    const stat = fs.statSync(absPath);
    if (stat.isDirectory()) {
      for (const entry of fs.readdirSync(absPath)) {
        scan(path.join(absPath, entry), path.join(rel, entry));
      }
      return;
    }
    if (!extensions.has(path.extname(absPath))) return;
    const src = fs.readFileSync(absPath, 'utf-8');
    const lines = src.split('\n');
    lines.forEach((line, i) => checkLine(line, rel, i + 1));
  };

  const full = path.join(rootDir, target);
  if (fs.existsSync(full)) scan(full, target);

  if (errors === 0) {
    console.log('✓ Skill prose validator: skills/impeccable/ is clean');
  } else {
    console.error(`\n❌ ${errors} prose issue(s) in skills/impeccable/. See STYLE.md.`);
  }
  return errors;
}

/**
 * Validate that every hand-authored HTML page carries the shared site header.
 * The partial is stamped with `<!-- site-header v1 -->` so drift is loud.
 *
 * Returns the number of validation errors. Build fails if > 0.
 */
function validateSiteHeader() {
  console.log('✓ Site header is a shared Astro component');
  return 0;
}

/**
 * Copy directory recursively
 */
function copyDirSync(src, dest) {
  fs.mkdirSync(dest, { recursive: true });
  const entries = fs.readdirSync(src, { withFileTypes: true });
  for (const entry of entries) {
    const srcPath = path.join(src, entry.name);
    const destPath = path.join(dest, entry.name);
    if (entry.isDirectory()) {
      copyDirSync(srcPath, destPath);
    } else {
      fs.copyFileSync(srcPath, destPath);
    }
  }
}

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const ROOT_DIR = path.resolve(__dirname, '..');
const DIST_DIR = path.join(ROOT_DIR, 'dist');

/**
 * Prepare a visible bundle README and optional Codex plugin metadata
 * inside each generated Codex distribution directory.
 */
function prepareCodexBundle(distDir, outputName) {
  const bundleDir = path.join(distDir, outputName);
  if (!fs.existsSync(bundleDir)) return;

  fs.writeFileSync(
    path.join(bundleDir, 'README.txt'),
`Impeccable for Codex CLI
https://impeccable.style
This bundle contains:

  skills/         → Codex plugin skills
  .codex-plugin/  → Codex plugin manifest
  .agents/        → Codex marketplace metadata

Install by extracting this bundle into your project root.
`
  );

  const pluginManifestPath = path.join(ROOT_DIR, 'plugins', 'impeccable', '.codex-plugin');
  if (fs.existsSync(pluginManifestPath)) {
    copyDirSync(pluginManifestPath, path.join(bundleDir, '.codex-plugin'));
  }

  const marketplacePath = path.join(ROOT_DIR, '.agents');
  if (fs.existsSync(marketplacePath)) {
    copyDirSync(marketplacePath, path.join(bundleDir, '.agents'));
  }

  console.log('✓ Prepared codex bundle');
}

/**
 * Generate static API data for Cloudflare Pages deployment.
 * Pre-builds all API responses as JSON files so they can be served
 * as static assets via _redirects rewrites (no function invocations needed).
 */
function generateApiData(buildDir, skills, patterns) {
  const apiDir = path.join(buildDir, '_data', 'api');
  fs.mkdirSync(apiDir, { recursive: true });

  // skills.json
  const skillsData = skills.map(s => ({
    id: path.basename(path.dirname(s.filePath)),
    name: s.name,
    description: s.description,
    userInvocable: s.userInvocable,
  }));
  fs.writeFileSync(path.join(apiDir, 'skills.json'), JSON.stringify(skillsData));

  // commands.json (user-invocable skills only)
  const commandsData = skillsData.filter(s => s.userInvocable);
  fs.writeFileSync(path.join(apiDir, 'commands.json'), JSON.stringify(commandsData));

  // patterns.json
  fs.writeFileSync(path.join(apiDir, 'patterns.json'), JSON.stringify(patterns));

  // command-source/{id}.json (one per skill)
  const cmdSourceDir = path.join(apiDir, 'command-source');
  fs.mkdirSync(cmdSourceDir, { recursive: true });
  for (const skill of skills) {
    const id = path.basename(path.dirname(skill.filePath));
    const content = fs.readFileSync(skill.filePath, 'utf-8');
    fs.writeFileSync(
      path.join(cmdSourceDir, `${id}.json`),
      JSON.stringify({ content })
    );
  }

  console.log(`✓ Generated static API data (${skillsData.length} skills, ${commandsData.length} commands)`);
}

/**
 * Generate Cloudflare Pages config files (_headers, _redirects)
 */
function generateCFConfig(buildDir) {
  // _headers: security + cache headers
  const headers = `/*
  X-Content-Type-Options: nosniff
  X-Frame-Options: SAMEORIGIN

# HTML pages: browser always revalidates, CDN caches 1h
/*.html
  Cache-Control: public, max-age=0, s-maxage=3600, stale-while-revalidate=600

# Hashed JS/CSS bundles: immutable (filename changes on content change)
/assets/*.js
  Cache-Control: public, max-age=31536000, immutable

/assets/*.css
  Cache-Control: public, max-age=31536000, immutable

# Static images and logos: 1 week + 1 day stale
/assets/*.png
  Cache-Control: public, max-age=604800, stale-while-revalidate=86400

/assets/*.svg
  Cache-Control: public, max-age=604800, stale-while-revalidate=86400

/assets/*.webp
  Cache-Control: public, max-age=604800, stale-while-revalidate=86400

/antipattern-images/*
  Cache-Control: public, max-age=604800, stale-while-revalidate=86400

# Root static assets (favicon, og-image, etc.)
/favicon.svg
  Cache-Control: public, max-age=604800, stale-while-revalidate=86400

/og-image.jpg
  Cache-Control: public, max-age=604800, stale-while-revalidate=86400

/apple-touch-icon.png
  Cache-Control: public, max-age=604800, stale-while-revalidate=86400

# ZIP downloads: 1h cache
/dist/*.zip
  Cache-Control: public, max-age=3600, stale-while-revalidate=600

# API routes: CDN caches 24h
/api/*
  Cache-Control: public, s-maxage=86400, stale-while-revalidate=3600

/_data/api/*
  Cache-Control: public, s-maxage=86400, stale-while-revalidate=3600
`;
  fs.writeFileSync(path.join(buildDir, '_headers'), headers);

  // _redirects: rewrite JSON API routes to static files (200 = rewrite, not redirect).
  // Keep public redirects from the old anti-pattern and visual-mode URLs.
  const redirects = `/api/skills /_data/api/skills.json 200
/api/commands /_data/api/commands.json 200
/api/patterns /_data/api/patterns.json 200
/api/command-source/:id /_data/api/command-source/:id.json 200
/anti-patterns /slop#catalog 301
/visual-mode /slop#see-it 301
`;
  fs.writeFileSync(path.join(buildDir, '_redirects'), redirects);

  // _routes.json: tell Cloudflare Pages which paths invoke Functions
  // Without this, the SPA fallback serves index.html for function routes
  const routes = {
    version: 1,
    include: ['/api/download/*'],
    exclude: [],
  };
  fs.writeFileSync(path.join(buildDir, '_routes.json'), JSON.stringify(routes, null, 2));

  console.log('✓ Generated Cloudflare Pages config (_headers, _redirects, _routes.json)');
}

/**
 * Main build process
 */
async function build() {
  console.log('🔨 Building Codex CLI design skills...\n');

  // Astro owns website rendering. This script prepares generated public
  // assets, Codex dist files, static API data, and Cloudflare config.
  const publicDir = path.join(ROOT_DIR, 'site', 'public');

  // Copy browser detector script (referenced by antipattern examples at /js/...)
  const detectorSrc = path.join(ROOT_DIR, 'cli', 'engine', 'detect-antipatterns-browser.js');
  if (fs.existsSync(detectorSrc)) {
    const jsDir = path.join(publicDir, 'js');
    fs.mkdirSync(jsDir, { recursive: true });
    fs.copyFileSync(detectorSrc, path.join(jsDir, 'detect-antipatterns-browser.js'));
  }

  // Read source files (unified skills architecture)
  const { skills } = readSourceFiles(ROOT_DIR);
  const patterns = readPatterns(ROOT_DIR);
  const userInvocableCount = skills.filter(s => s.userInvocable).length;
  console.log(`📖 Read ${skills.length} skills (${userInvocableCount} user-invocable) and ${patterns.patterns.length + patterns.antipatterns.length} pattern categories\n`);

  const packageJson = JSON.parse(fs.readFileSync(path.join(ROOT_DIR, 'package.json'), 'utf-8'));
  const skillsVersion = packageJson.version;

  if (fs.existsSync(DIST_DIR)) fs.rmSync(DIST_DIR, { recursive: true, force: true });

  // Transform for the canonical Codex provider.
  for (const config of Object.values(PROVIDERS)) {
    const transform = createTransformer(config);
    transform(skills, DIST_DIR, { skillsVersion });
  }

  prepareCodexBundle(DIST_DIR, 'codex');

  // Create the canonical Codex distribution ZIP.
  await createAllZips(DIST_DIR);

  // Generate static API data and Cloudflare Pages config into public/ so
  // Astro copies them into build/. Astro wipes build/ at the start of its run.
  generateApiData(publicDir, skills, patterns);
  generateCFConfig(publicDir);

  // Copy Codex output to the repo root for local testing.
  const syncConfig = PROVIDERS.codex;
  const skillsSrc = path.join(DIST_DIR, syncConfig.provider, syncConfig.skillsPath);
  const skillsDest = path.join(ROOT_DIR, 'plugins', 'impeccable', syncConfig.skillsPath);

  if (fs.existsSync(skillsSrc)) {
    const stashed = stashPerProjectArtifacts(skillsDest);
    if (fs.existsSync(skillsDest)) fs.rmSync(skillsDest, { recursive: true });
    copyDirSync(skillsSrc, skillsDest);
    restorePerProjectArtifacts(skillsDest, stashed);
  }

  // Remove deprecated skill stubs from local harness dirs. They exist
  // in dist/ so the cleanup script can redirect users, but they should
  // not clutter the repo's own skill directories.
  const deprecatedLocalSkills = [
    'frontend-design', 'teach-impeccable',
    'arrange', 'normalize', 'extract',
  ];
  for (const name of deprecatedLocalSkills) {
    const p = path.join(ROOT_DIR, 'plugins', 'impeccable', syncConfig.skillsPath, name);
    if (fs.existsSync(p)) fs.rmSync(p, { recursive: true, force: true });
  }

  console.log(`📋 Synced skills to: plugins/impeccable/${syncConfig.skillsPath}`);


  // Generate authoritative counts and validate references
  const countErrors = generateCounts(ROOT_DIR, skills);

  // Cross-validate engine rules against impeccable SKILL.md DON'Ts
  const validationErrors = validateAntipatternRules(ROOT_DIR);

  // Verify every hand-authored HTML page carries the shared site header
  const headerErrors = validateSiteHeader();

  // Scan user-facing copy for AI tells (em dashes, marketing fluff, denylisted phrases)
  const proseErrors = validateProse(ROOT_DIR);

  // Scan canonical skill source for mechanical prose drift
  const skillProseErrors = validateSkillProse(ROOT_DIR);

  if (countErrors > 0 || validationErrors > 0 || headerErrors > 0 || proseErrors > 0 || skillProseErrors > 0) {
    process.exit(1);
  }

  console.log('\n✨ Build complete!');
}

// Run the build
build();
